# Site settings
title: Shivani Bhatia
email: scbhatia@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Shivani Bhatia
email: scbhatia@bu.edu
facebook_username: shivanicbhatia
linkedin_username: shivanicbhatia
github_username: scbhatia
address: 
  - line: 820 Beacon St
  - line: Boston, MA 02215
  # Feel free to add more lines here 
telephone: 267-885-8880
copyright:

# API settings
google_api_key: AIzaSyCylrL7uNlV7c9hlZ9t-ADGJx8O-HIkK_U

# Build settings
markdown: kramdown